### ISSUE TITLE
bug: 마이크 입력 감도 문제

### ISSUE THREAD

**Issue by marmot8080** [marmot8080/Soom-Charm#3]
현재 Feature/breath_analyzer 브랜치에 업데이트한 코드를 테스트 해 본 결과 정상적으로 작동은 되지만 마이크 입력 감도가 좀 낮다는 생각이 듭니다.
이에 대한 해결 방법이나 의견이 있으시다면 의견 남겨주시면 감사하겠습니다.

**Comment by Hyunjiiing** [comment]
혹시 단위가 dB인가요? 
바람을 불었을 때 처음에는 1000dB로 인식하다가 다음에 바람을 불었을 때는 계속 100dB로 측정 된다는 말씀이신거죠?

**Comment by marmot8080** [comment]
단위가 정확히 dB인지는 확인하지는 못했습니다.
위에 말씀 드린 값은 마이크로 인식된 소리 중 0Hz~200Hz 사이의 소리로 감지되는 값들을 모두 합한 값입니다.
(바람소리가 저주파 대역의 소리의 비중이 크기 때문에 저주파 대역의 소리의 값의 합으로 판별하는 방식입니다.)

Kotlin으로 했을 때와의 마이크 감도가 다른 것으로 보아 하드웨어의 문제는 아닐 것으로 예상하고, 아마 라이브러리의 차이가 아닐까 예상 중입니다.

**Comment by marmot8080** [comment]
추가적으로 주변 소음이 많을 경우, 저주파 대역의 소리도 많이 인식되어 호흡을 제대로 감지하지 못하는 경우가 많은 것 같습니다.
이에 대해 일단 게임 실행 전 주의 메시지 및 마이크 테스트 화면을 별도로 구성하는 것이 최선이라고 생각됩니다.
혹시 다른 의견이 있으시다면 말씀해주시면 감사하겠습니다.

**Comment by marmot8080** [comment]
https://github.com/llfbandit/record/issues/404
위의 이슈에서도 같은 문제를 지적한 것 같습니다.
답변을 보면 최근 커밋에 해당 문제점을 반영했고 이후부터는 객체를 생성할 때 audio source를 mic로 지정해주거나 하면 해결될 것 같습니다.
최근 커밋이라 아직 라이브러리의 최신 버전에는 반영되지 않았지만 이후 버전에는 반영될 것으로 보입니다.

**Comment by marmot8080** [comment]
이러면 당장은 호흡의 세기 등을 측정하는 기능은 활용하지 못하겠지만 개인적인 생각으로는 record 라이브러리를 다른 라이브러리로 대체하지는 않아도 될 것 같습니다.

**Comment by Hyunjiiing** [comment]
넵 알겠습니다. 미니게임에 호흡 감지 기능을 넣을 때 참고하여 record 라이브러리로 개발하겠습니다.
혹시나 이후 버전에도 반영되지 않았을 시에 다른 라이브러리로 시도해보겠습니다.

**Comment by marmot8080** [comment]
https://github.com/FlutterFlow/flutterflow-issues/issues/2749#issuecomment-2434190588
위의 이슈를 확인해보고 useLagcy: true를 추가해봤지만 아래와 같은 오류가 발생했습니다.
```
E/DartMessenger(15198): Uncaught exception in binary message listener
E/DartMessenger(15198): java.lang.Exception: Unsupported feature from legacy recorder.
E/DartMessenger(15198): 	at com.llfbandit.record.methodcall.RecorderWrapper.startRecordingToStream(RecorderWrapper.kt:53)
E/DartMessenger(15198): 	at com.llfbandit.record.methodcall.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.kt:83)
E/DartMessenger(15198): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/DartMessenger(15198): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/DartMessenger(15198): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/DartMessenger(15198): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(15198): 	at android.os.Handler.handleCallback(Handler.java:958)
E/DartMessenger(15198): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(15198): 	at android.os.Looper.loopOnce(Looper.java:205)
E/DartMessenger(15198): 	at android.os.Looper.loop(Looper.java:294)
E/DartMessenger(15198): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/DartMessenger(15198): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(15198): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/DartMessenger(15198): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
I/flutter (15198): Error starting breath detection: MissingPluginException(No implementation found for method startStream on channel com.llfbandit.record/messages)
```
